apiVersion: v1
kind: Pod
metadata:
  name: mynaspod
spec:
  containers:
    - name: "nginx-flexvolume-nas-pvc"
      image: "tutum/hello-world"
      volumeMounts:
          - name: pvc-nas
            mountPath: "/data"
  volumes:
  - name: pvc-nas
    persistentVolumeClaim:
        claimName: mynaspvc
