apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mynaspvc
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: cds-nas-sc
