apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cds-nas-sc
provisioner: cds/nas
reclaimPolicy: Delete
parameters:
  servers: 1.2.3.4/nfsshare, 1.2.3.5/nfsshare
  #server: 1.2.3.4
  #path: /nfsshare
  vers: "4.1"
  archiveOnDelete: "true"
